### ISSUE TITLE
AWS::Serverless::Application SAM resource deployment fails for multiple stacks

### ISSUE THREAD

**Issue by mccauleyp** [awslabs/aws-data-wrangler#877]
**Describe the bug**

Deploying `aws-data-wrangler` as a Lambda layer as a SAM resource is currently limited to one CloudFormation stack per account. Trying to deploy to multiple stacks fails I think because the stack name isn't appended to the export name. 

https://serverlessrepo.aws.amazon.com/applications/us-east-1/336392948345/aws-data-wrangler-layers

Clicking `Deploy` on the page above shows the following template:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  AWS Data Wrangler Lambda layers (SAR)
Resources:
  WranglerLayer37:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-data-wrangler-2_10_0-py3_7
      ContentUri:
        Bucket: <%REPO_BUCKET%>
        Key: 57943132-39fa-4365-b017-dda1961ccede
      Description: AWS Data Wrangler Lambda Layer - 2.10.0 (Python 3.7)
      LicenseInfo: Apache 2.0
      CompatibleRuntimes:
      - python3.7
  WranglerLayer38:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-data-wrangler-2_10_0-py3_8
      ContentUri:
        Bucket: <%REPO_BUCKET%>
        Key: 7d185455-7229-46b7-8008-0ac88427603e
      Description: AWS Data Wrangler Lambda Layer - 2.10.0 (Python 3.8)
      LicenseInfo: Apache 2.0
      CompatibleRuntimes:
      - python3.8
Outputs:
  WranglerLayer37Arn:
    Value:
      Ref: WranglerLayer37
    Export:
      Name: aws-data-wrangler-2-10-0-py3-7
  WranglerLayer38Arn:
    Value:
      Ref: WranglerLayer38
    Export:
      Name: aws-data-wrangler-2-10-0-py3-8
```

I think the export names at the bottom should be something like...

```
Outputs:
  WranglerLayer37Arn:
    Value:
      Ref: WranglerLayer37
    Export:
      Name: 
        Fn::Sub: WranglerLayer37Arn-${AWS::StackName}
  WranglerLayer38Arn:
    Value:
      Ref: WranglerLayer38
    Export:
      Name: 
        Fn::Sub: WranglerLayer38Arn-${AWS::StackName}
```

I lifted the `Fn::Sub` model above from the `aws-lambda-powertools` package:

https://serverlessrepo.aws.amazon.com/applications/eu-west-1/057560766410/aws-lambda-powertools-python-layer

Their template looks like:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda Layer for aws-lambda-powertools with python3.8, 3.7 or 3.6
Resources:
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: AWS Lambda Layer for aws-lambda-powertools version 1.20.1
      LayerName: aws-lambda-powertools-python-layer
      ContentUri:
        Bucket: <%REPO_BUCKET%>
        Key: 8dff53ba-fad2-4497-b119-c94526433900
      CompatibleRuntimes:
      - python3.9
      - python3.8
      - python3.7
      - python3.6
      LicenseInfo: Available under the Apache-2.0 license.
      RetentionPolicy: Retain
Outputs:
  LayerVersionArn:
    Description: ARN for the published Layer version
    Value:
      Ref: LambdaLayer
    Export:
      Name:
        Fn::Sub: LayerVersionArn-${AWS::StackName}
```

**Environment**

I'm deploying via Serverless Framework. I get the SAM resource snippet from the `Copy as SAM Resource` buttons at the links above, and my resource file looks like:

```
Transform: AWS::Serverless-2016-10-31
Resources:
  AwsLambdaPowertoolsPythonLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer
        # Find latest from github.com/awslabs/aws-lambda-powertools-python/releases
        SemanticVersion: 1.19.0

  AwsDataWranglerLayers:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:336392948345:applications/aws-data-wrangler-layers
         # Find latest from github.com/awslabs/aws-data-wrangler/releases
        SemanticVersion: 2.10.0
```

This works for one stack, but the `AwsDataWranglerLayers` part causes an error when attempting the deploy to a second stack for the reason described above. 

**To Reproduce**

Deploy the above via CloudFormation to two stacks in the same account. I'm using `serverless deploy --stage="stack_name"` to do the deployment. I get the following error for the second stack:

```
AwsDataWranglerLayers - Embedded stack arn:aws:cloudformation:{region}:{account}:stack/{stack_name}-AwsDataWranglerLayers-{cf_id}/{hash} was not successfully created: Export with name aws-data-wrangler-2-10-0-py3-7 is already exported by stack {stack_name}-AwsDataWranglerLayers-{cf_id}.
```

*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
